#!/usr/bin/bash
set -ex

# qwen3_5 mpirun launch script, adapted from the kimi_k3 mpi_train.sh in the
# guojihu/torchtitan repo (itself based on mvb4's mpi_train_B300.sh).
#
# This repo selects a run via a Python config registry instead of TOML files:
#   --module qwen3_5 --config <function in models/qwen3_5/config_registry.py>
# Available configs: qwen35_debugmodel, qwen35_debugmodel_moe, qwen35_0_8b,
# qwen35_2b, qwen35_4b, qwen35_9b, qwen35_27b, qwen35_35b_a3b,
# qwen35_122b_a10b, qwen35_397b_a17b (see config_registry.py).
#
# Usage:
#   bash torchtitan/models/qwen3_5/mpi_train.sh                    # qwen35_debugmodel
#   bash torchtitan/models/qwen3_5/mpi_train.sh qwen35_0_8b        # pick a config
#   bash torchtitan/models/qwen3_5/mpi_train.sh qwen35_debugmodel \
#       --training.steps 20                                        # extra CLI overrides
#   NP=2 CUDA_VISIBLE_DEVICES=6,7 bash .../mpi_train.sh            # limit GPUs
#   HOSTFILE=none bash .../mpi_train.sh                            # force single-node
#
# Verified 2026-08-19 on the 4-node B300 cluster (torch 2.13.0+cu132,
# python 3.12, kml task 100044149): qwen35_debugmodel, 32 ranks, loss
# 12.85 -> 2.38 in 10 steps. Notes from that bring-up:
#   - qwen35_debugmodel keeps training.seq_len=512, but the cc12m-test debug
#     dataset has almost no multimodal samples that short: every rank spins in
#     "Sample length > seq_len. Skip" and no step ever completes. Pass
#     --training.seq_len 4096 when running the debug configs on cc12m.
#   - Manual runs over raw ssh must use a login shell (bash -lc): the xray
#     mpirun wrapper needs OPAL_PREFIX etc. from /etc/profile.d, otherwise
#     the hpcx orterun cannot even parse --allow-run-as-root.
#
# Compared to the mvb4 script this drops NCCL_MIN_NCHANNELS=32 /
# NCCL_IB_QPS_PER_CONNECTION=8: on shared dev machines MIN_NCHANNELS=32 made
# FSDP reduce_scatter/all_gather deadlock against co-located jobs (600s
# timeouts, varying hang points). Multi-node production runs that own the
# whole machine can add them back.

# ============================================================================
# 1. Path resolution
# ============================================================================
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
WORKSPACE=$(cd "${SCRIPT_DIR}/../../.." && pwd)

echo "Script Dir:   ${SCRIPT_DIR}"
echo "Workspace:    ${WORKSPACE}"

# ============================================================================
# 2. Environment and configuration
# ============================================================================
# Multi-node uses the IP-sorted hostfile_seq (generated by kai_launch);
# single-node (including KML jobs whose hostfile only lists this machine)
# starts local ranks by GPU count. HOSTFILE=none forces single-node even when
# /etc/mpi/hostfile lists multiple machines.
HOSTFILE=${HOSTFILE:-}
if [ "$HOSTFILE" = "none" ]; then
    HOSTFILE=
elif [ -f /etc/mpi/hostfile -a -z "$HOSTFILE" ]; then
    N_HOSTS=$(grep -v '^#' /etc/mpi/hostfile | awk '{print $1}' | sort -u | wc -l)
    if [ "$N_HOSTS" -gt 1 ]; then
        if [ ! -f /etc/mpi/hostfile_seq ]; then
            echo "Please use kai_launch to generate /etc/mpi/hostfile_seq"
            exit 1
        fi
        HOSTFILE=/etc/mpi/hostfile_seq
    else
        echo "hostfile only contains this node; running in single-node mode"
    fi
fi
if [ -n "$HOSTFILE" ]; then
    # Multi-node job
    if [ -z "${MY_NODE_IP:-}" ]; then echo "Variable MY_NODE_IP does not exist."; exit 1; fi
    if ! ifconfig | grep " $MY_NODE_IP " >/dev/null; then echo "MY_NODE_IP \"$MY_NODE_IP\" is not contained in \`ifconfig\`."; exit 1; fi
    MASTER_ADDR=$MY_NODE_IP
    if [ ! -f "$HOSTFILE" ]; then echo "Hostfile \"$HOSTFILE\" does not exist."; exit 1; fi
    NP=${NP:-$(cat "$HOSTFILE" | grep -v '^#' | grep -oP 'slots=\K\d+' | awk '{sum += $1} END {print sum}')}
    HOSTFILE_OPTS="-hostfile $HOSTFILE"
else
    # Single-node job
    MASTER_ADDR=127.0.0.1
    if [ -n "${CUDA_VISIBLE_DEVICES:-}" ]; then
        NP=${NP:-$(echo "$CUDA_VISIBLE_DEVICES" | tr ',' '\n' | wc -l)}
    else
        NP=${NP:-$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)}
    fi
    HOSTFILE_OPTS=
fi
MASTER_PORT=${MASTER_PORT:-29500}

# Multi-node defaults to bond0 (B300 cluster); single-node binds no NIC.
# Override with NET_IFNAME.
IFACE_OPTS=
if [ -n "$HOSTFILE" ]; then
    NET_IFNAME=${NET_IFNAME:-bond0}
fi
if [ -n "${NET_IFNAME:-}" ]; then
    IFACE_OPTS="
    -x NCCL_SOCKET_IFNAME=${NET_IFNAME}
    -x OMPI_MCA_oob_tcp_if_include=${NET_IFNAME}
    -x OMPI_MCA_btl_tcp_if_include=${NET_IFNAME}
    "
fi

# KCCL LD_PRELOAD policy (the platform wrapper injects it per machine type;
# multi-node also carries KCCL_PROFILER_TASK_RUNID for platform monitoring):
# keep it by default on multi-node -- same as mvb4 production and the platform
# agent may depend on it; clear it by default on single-node -- kccl
# 2.27.7-cuda12 preload deadlocked FSDP reduce_scatter/all_gather on dev
# machines (independently of NCCL_MIN_NCHANNELS=32, see 2026-08-04 notes).
# QWEN35_LD_PRELOAD=<so path> to swap the lib, =none to force-clear.
if [ -z "${QWEN35_KEEP_WRAPPER_PRELOAD:-}" ]; then
    if [ -n "$HOSTFILE" ]; then
        QWEN35_KEEP_WRAPPER_PRELOAD=1
    else
        QWEN35_KEEP_WRAPPER_PRELOAD=0
    fi
fi

# Interpreter: explicit PYTHON= wins; on single-node use /tmp/qwen35_venv if
# present (python 3.11 venv with torch 2.9.1+cu128, fla, tyro etc. -- this
# repo needs python >= 3.11); multi-node defaults to the container python
# (image must ship python >= 3.11 with the deps in requirements.txt).
if [ -z "${PYTHON:-}" ]; then
    if [ -z "$HOSTFILE" ] && [ -x /tmp/qwen35_venv/bin/python3 ]; then
        PYTHON=/tmp/qwen35_venv/bin/python3
    else
        PYTHON=python
    fi
fi
export PYTHON

# Only forward CUDA_VISIBLE_DEVICES when explicitly set (forwarding an empty
# value via -x hides all GPUs)
GPU_OPTS=
if [ -n "${CUDA_VISIBLE_DEVICES:-}" ]; then
    GPU_OPTS="-x CUDA_VISIBLE_DEVICES"
fi

cd ${WORKSPACE}

# First positional arg picks the config registry function; the rest are
# forwarded to the trainer CLI (e.g. --training.steps 20). Word splitting
# applies to the forwarded args, so avoid values with spaces.
export MODULE=${MODULE:-qwen3_5}
if [ -n "${1:-}" ]; then
    export CONFIG="$1"
    shift
else
    export CONFIG=${CONFIG:-qwen35_debugmodel}
fi

# Workarounds verified on torch 2.13.0+cu132 (2026-08-19), injected before the
# user's extra args so an explicit flag on the command line wins:
# - spmd_backend: the registry default is spmd_types, but under spmd_types
#   model.parallelize only annotates plain local tensors (spmd.shard), while
#   this torch's fully_shard(dp_mesh_dims=...) requires real DTensors on the
#   full SPMD mesh -- every multi-rank run dies in apply_fsdp_to_vision_encoder
#   with "all parameters must be DTensors". partial_dtensor takes the classic
#   FSDP path (dp_mesh_dims=None) and trains fine. QWEN35_SPMD_BACKEND=none
#   keeps the registry default once spmd_types is usable.
# - CUDA graphs: the trainer wraps fwd/bwd in CUDA graphs by default, but the
#   qwen3_5 multimodal input path does unpinned host-to-device copies during
#   capture ("Cannot copy between CPU and CUDA tensors during CUDA graph
#   capture"). QWEN35_CUDA_GRAPHS=1 re-enables graphs.
DEFAULT_ARGS=
QWEN35_SPMD_BACKEND=${QWEN35_SPMD_BACKEND:-partial_dtensor}
if [ "$QWEN35_SPMD_BACKEND" != "none" ]; then
    DEFAULT_ARGS="--parallelism.spmd_backend $QWEN35_SPMD_BACKEND"
fi
if [ "${QWEN35_CUDA_GRAPHS:-0}" != "1" ]; then
    DEFAULT_ARGS="$DEFAULT_ARGS --training.disable_cuda_graphs"
fi
export TRAIN_EXTRA_ARGS="$DEFAULT_ARGS $*"

if ! $PYTHON - "$MODULE" "$CONFIG" <<'EOF'
import importlib, sys
module = importlib.import_module(f"torchtitan.models.{sys.argv[1]}.config_registry")
sys.exit(0 if callable(getattr(module, sys.argv[2], None)) else 1)
EOF
then
    echo "ERROR: config '$CONFIG' not found in torchtitan.models.$MODULE.config_registry"
    exit 1
fi

export PYTORCH_ALLOC_CONF=expandable_segments:True

# Experiment directory: outputs/<config>. Trainer artifacts (tensorboard,
# checkpoints, profiling) and launcher logs all land under it.
DUMP_FOLDER=${DUMP_FOLDER:-outputs/${CONFIG}}
case "$DUMP_FOLDER" in
    ./*) DUMP_FOLDER="${WORKSPACE}/${DUMP_FOLDER#./}" ;;
    /*)  ;;
    *)   DUMP_FOLDER="${WORKSPACE}/${DUMP_FOLDER}" ;;
esac
export DUMP_FOLDER

LOG_DIR="${DUMP_FOLDER}/log"
mkdir -p $LOG_DIR
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# Redirect all further output through tee: write the log file and the screen
exec > >(tee "${LOG_DIR}/train_output_${TIMESTAMP}.log") 2>&1
echo "Total GPUs (np): $NP"
echo "Module/Config:   $MODULE / $CONFIG"
echo "Dump folder:     $DUMP_FOLDER"
echo "Python:          $PYTHON"
[ -n "$TRAIN_EXTRA_ARGS" ] && echo "Extra args:      $TRAIN_EXTRA_ARGS"

# Disable python output buffering so logs are written in real time
export PYTHONUNBUFFERED=1

# ============================================================================
# 3. Run training
# ============================================================================
/opt/xray/deps/mpirun --allow-run-as-root -np $NP --mca orte_abort_on_non_zero_status 1 \
    $HOSTFILE_OPTS \
    $IFACE_OPTS \
    $GPU_OPTS \
    -x HOROVOD_MPI_THREADS_DISABLE=1 \
    -x MPI_THREAD_SINGLE=1 \
    -x PATH \
    -bind-to none -map-by slot \
    --mca btl tcp,self \
    -mca coll_ucc_enable 0 \
    -x NCCL_IB_DISABLE=0 \
    -x NCCL_IB_GID_INDEX=3 \
    -x NCCL_DEBUG=WARN \
    -x OMPI_MCA_btl=self,tcp \
    -x NCCL_NET_PLUGIN=none \
    -x OMPI_MCA_btl_openib_allow_ib=false \
    -x OMPI_MCA_pml=ob1 \
    -x NCCL_IB_ECE_ENABLE=0 \
    -x NCCL_NVLS_ENABLE=0 \
    -x NCCL_IB_TIMEOUT=21 \
    -x NCCL_ASYNC_ERROR_HANDLING=1 \
    -x TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=2400 \
    -x NCCL_TIMEOUT=2400 \
    -x PYTORCH_ALLOC_CONF \
    -x TORCH_GLOO_LAZY_INIT=0 \
    -x GLOO_ENABLE_STORE_V2_API=1 \
    -x GLOO_ENABLE_RANK_AS_SEQUENCE_NUMBER=1 \
    -x MASTER_ADDR=$MASTER_ADDR \
    -x MASTER_PORT=$MASTER_PORT \
    -x MODULE \
    -x CONFIG \
    -x DUMP_FOLDER \
    -x TRAIN_EXTRA_ARGS \
    -x PYTHON \
    -x TORCH_ALLOW_TF32_CUBLAS_OVERRIDE=0 \
    -x PYTHONUNBUFFERED \
    -x QWEN35_LD_PRELOAD="${QWEN35_LD_PRELOAD:-}" \
    -x QWEN35_KEEP_WRAPPER_PRELOAD="${QWEN35_KEEP_WRAPPER_PRELOAD}" \
    -x TRITON_PTXAS_PATH="${TRITON_PTXAS_PATH:-}" \
    bash ${SCRIPT_DIR}/wrap_mpi_signal.sh bash -c '
        export LOCAL_RANK=$OMPI_COMM_WORLD_LOCAL_RANK
        export RANK=$OMPI_COMM_WORLD_RANK
        export WORLD_SIZE=$OMPI_COMM_WORLD_SIZE
        # Some production images (e.g. wlf2 py3.12) ship a triton without a
        # bundled ptxas, so fla kernel compilation fails with "Cannot find
        # ptxas". Only fall back to the cuda toolchain when triton really has
        # no bundled ptxas, to avoid changing the verified compiler version on
        # older images (triton 3.2 bundles ptxas).
        if [ -z "${TRITON_PTXAS_PATH:-}" ] && [ -x /usr/local/cuda/bin/ptxas ]; then
            if ! $PYTHON -c "import os, triton; p = os.path.join(os.path.dirname(triton.__file__), \"backends\", \"nvidia\", \"bin\", \"ptxas\"); raise SystemExit(0 if os.path.exists(p) else 1)" >/dev/null 2>&1; then
                export TRITON_PTXAS_PATH=/usr/local/cuda/bin/ptxas
            fi
        fi
        if [ -z "${TRITON_PTXAS_PATH:-}" ]; then unset TRITON_PTXAS_PATH; fi
        # LD_PRELOAD decision: see the QWEN35_KEEP_WRAPPER_PRELOAD comment above
        if [ -n "${QWEN35_LD_PRELOAD:-}" ]; then
            if [ "$QWEN35_LD_PRELOAD" = "none" ]; then
                unset LD_PRELOAD
            else
                export LD_PRELOAD="$QWEN35_LD_PRELOAD"
            fi
        elif [ "${QWEN35_KEEP_WRAPPER_PRELOAD:-1}" != "1" ]; then
            unset LD_PRELOAD
        fi
        $PYTHON -m torchtitan.train \
            --module $MODULE \
            --config $CONFIG \
            --dump_folder $DUMP_FOLDER \
            $TRAIN_EXTRA_ARGS
    '

# No pipe here, so $? is mpirun's exit code
RET=$?
if [ $RET -ne 0 ]; then
    echo "Training failed with exit code $RET"
    exit $RET
fi
exit 0
